- name: install dovecot
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ dovecot_packages }}"

- name: listen
  lineinfile:
    backup: yes
    path: /etc/dovecot/dovecot.conf
    state: present
    insertafter: '#listen'
    regexp: '^listen'
    line: 'listen = *'

- name: protocols
  lineinfile:
    backup: no
    path: /etc/dovecot/dovecot.conf
    state: present
    insertafter: '#protocols'
    regexp: '^protocols'
    line: 'protocols = imap pop3'

- name: disable_plaintext_auth
  lineinfile:
    backup: yes
    path: /etc/dovecot/conf.d/10-auth.conf
    state: present
    insertafter: '#disable_plaintext_auth'
    regexp: '^disable_plaintext_auth'
    line: 'disable_plaintext_auth = yes'

- name: auth_mechanisms
  lineinfile:
    backup: no
    path: /etc/dovecot/conf.d/10-auth.conf
    state: present
    insertafter: 'auth_mechanisms'
    regexp: '^auth_mechanisms'
    line: 'auth_mechanisms = digest-md5 cram-md5'

- name: mail_location
  lineinfile:
    backup: yes
    path: /etc/dovecot/conf.d/10-mail.conf
    state: present
    insertafter: '#mail_location'
    regexp: '^mail_location'
    line: 'mail_location = maildir:~/Maildir'

- name: create dhparams
  shell: openssl dhparam -out dhparams.pem 2048
  args:
    chdir: /etc/dovecot/
    creates: /etc/dovecot/dhparams.pem

- name: ssl
  lineinfile:
    backup: yes
    path: /etc/dovecot/conf.d/10-ssl.conf
    state: present
    insertafter: '#ssl *='
    regexp: '^ssl *='
    line: 'ssl = no'

- name: ssl_dh_parameters_length
  lineinfile:
    backup: no
    path: /etc/dovecot/conf.d/10-ssl.conf
    state: present
    insertafter: '#ssl_dh_parameters_length'
    regexp: '^ssl_dh_parameters_length'
    line: 'ssl_dh_parameters_length = 2048'

- name: ssl_dh
  lineinfile:
    backup: no
    path: /etc/dovecot/conf.d/10-ssl.conf
    state: present
    insertafter: '#ssl_dh *='
    regexp: '^ssl_dh *='
    line: 'ssl_dh = </etc/dovecot/dhparams.pem'

- name: ssl_protocols
  lineinfile:
    backup: no
    path: /etc/dovecot/conf.d/10-ssl.conf
    state: present
    insertafter: '#ssl_protocols'
    regexp: '^ssl_protocols'
    line: 'ssl_protocols = !SSLv2 !SSLv3'

- name: ssl_cipher_list
  lineinfile:
    backup: no
    path: /etc/dovecot/conf.d/10-ssl.conf
    state: present
    insertafter: '#ssl_cipher_list'
    regexp: '^ssl_cipher_list'
    line: 'ssl_cipher_list = ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA'

- name: ssl_prefer_server_ciphers
  lineinfile:
    backup: no
    path: /etc/dovecot/conf.d/10-ssl.conf
    state: present
    insertafter: '#ssl_prefer_server_ciphers'
    regexp: '^ssl_prefer_server_ciphers'
    line: 'ssl_prefer_server_ciphers = yes'

- service:
    name: dovecot
    state: started

- service:
    name: dovecot
    enabled: yes
