- name: <postfix> install postfix
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ postfix_packages }}"

- name: <postfix> create dhparams
  shell: openssl dhparam -out dhparams.pem 2048
  args:
    chdir: /etc/postfix/
    creates: /etc/postfix/dhparams.pem

- name: <postfix> create dummy cert
  shell: /etc/pki/tls/certs/make-my-dummy-cert postfix.pem
  args:
    chdir: /etc/pki/tls/certs
    creates: /etc/pki/tls/certs/postfix.pem

- name: <postfix> modify permission of dummy cert
  file:
    path: /etc/pki/tls/certs/postfix.pem
    state: file
    owner: root
    group: root
    mode: 0644

- name: <postfix> modify config (smtp submission)
  blockinfile:
    state: present
    block: "{{ lookup('file', './postfix/master.cf.smtp-submission.template') }}"
    marker: "### # {mark} ANSIBLE MANAGED BLOCK : SMTP Submission ###"
    insertafter: "^#submission"
    dest: "/etc/postfix/master.cf"
    backup: yes

- name: <postfix> modify config (smtps)
  blockinfile:
    state: present
    block: "{{ lookup('file', './postfix/main.cf.smtps.template') }}"
    marker: "### # {mark} ANSIBLE MANAGED BLOCK : SMTPS ###"
    dest: "/etc/postfix/main.cf"
    backup: yes

- name: <postfix> modify config (sasl auth)
  blockinfile:
    state: present
    block: "{{ lookup('file', './postfix/main.cf.sasl.template') }}"
    marker: "### # {mark} ANSIBLE MANAGED BLOCK : SASL ###"
    dest: "/etc/postfix/main.cf"
    backup: no

- name: <postfix> modify config (smtp restrictions)
  blockinfile:
    state: present
    block: "{{ lookup('file', './postfix/main.cf.smtp-restriction.template') }}"
    marker: "### # {mark} ANSIBLE MANAGED BLOCK : SMTP RESTRICTIONS ###"
    dest: "/etc/postfix/main.cf"
    backup: no

- name: <postfix> myhostname
  lineinfile:
    backup: no
    path: /etc/postfix/main.cf
    state: present
    insertafter: '#myhostname'
    regexp: '^myhostname'
    line: 'myhostname = {{ myhostname }}'

- name: <postfix> mydomain
  lineinfile:
    backup: no
    path: /etc/postfix/main.cf
    state: present
    insertafter: '#mydomain'
    regexp: '^mydomain'
    line: 'mydomain = {{ mydomain }}'

- name: <postfix> myorigin
  lineinfile:
    backup: no
    path: /etc/postfix/main.cf
    state: present
    insertafter: '#myorigin'
    regexp: '^myorigin'
    line: 'myorigin = {{ myorigin }}'

- name: <postfix> mydestination
  lineinfile:
    backup: no
    path: /etc/postfix/main.cf
    state: present
    insertafter: '#mydestination'
    regexp: '^mydestination'
    line: 'mydestination = {{ mydestination }}'

- name: <postfix> inet_interfaces
  lineinfile:
    backup: no
    path: /etc/postfix/main.cf
    state: present
    insertafter: '#inet_interfaces'
    regexp: '^inet_interfaces'
    line: 'inet_interfaces = all'

- name: <postfix> home_mailbox
  lineinfile:
    backup: no
    path: /etc/postfix/main.cf
    state: present
    insertafter: '#home_mailbox'
    regexp: '^home_mailbox'
    line: 'home_mailbox = Maildir/'

- name: <postfix> start postfix
  service:
    name: postfix
    state: started

- name: <postfix> enable postfix
  service:
    name: postfix
    enabled: yes

- name: <saslauthd> start saslauthd
  service:
    name: saslauthd
    state: started

- name: <saslauthd> enable saslauthd
  service:
    name: saslauthd
    enabled: yes
