- name: setup nginx
  include: nginx.yml

- name: setup php-fpm
  include: php-fpm.yml

- name: iptables http
  lineinfile:
    backup: yes
    path: /etc/sysconfig/iptables
    state: present
    insertbefore: 'COMMIT'
    regexp: '^-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT'
    line: '-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT'

- name: iptables https
  lineinfile:
    backup: no
    path: /etc/sysconfig/iptables
    state: present
    insertbefore: 'COMMIT'
    regexp: '^-A INPUT -p tcp -m tcp --dport 443 -j ACCEPT'
    line: '-A INPUT -p tcp -m tcp --dport 443 -j ACCEPT'
