- name: <nginx> install nginx
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ nginx_packages }}"

- name: <nginx> create document root
  file:
    path: "{{ doc_root }}"
    state: directory
    recurse: yes
    owner: nginx
    group: nginx
    mode: 0775

- name: <nginx> nginx.conf
  template:
    backup: yes
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644

- name: <nginx> www.conf
  template:
    backup: yes
    src: templates/www.conf.j2
    dest: /etc/nginx/conf.d/www.conf
    owner: root
    group: root
    mode: 0644

- name: <nginx> php-fpm.conf
  template:
    backup: yes
    src: templates/php-fpm.conf.j2
    dest: /etc/nginx/default.d/php-fpm.conf
    owner: root
    group: root
    mode: 0644

- name: <nginx> nginx_status.conf
  template:
    backup: yes
    src: templates/nginx_status.conf.j2
    dest: /etc/nginx/default.d/nginx_status.conf
    owner: root
    group: root
    mode: 0644

- name: <nginx> create dummy cert
  shell: /etc/pki/tls/certs/make-my-dummy-cert nginx.pem
  args:
    chdir: /etc/pki/tls/certs
    creates: /etc/pki/tls/certs/nginx.pem

- name: <nginx> modify permission of dummy cert
  file:
    path: /etc/pki/tls/certs/nginx.pem
    state: file
    owner: root
    group: root
    mode: 0644

- name: <nginx> create dhparam
  shell: openssl dhparam -out dhparams.pem 2048
  args:
    chdir: /etc/nginx/
    creates: /etc/nginx/dhparams.pem

- name: <nginx> start nginx
  service:
    name: nginx
    state: started

- name: <nginx> enable nginx
  service:
    name: nginx
    enabled: yes
