- name: <php> install remi repo
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: present

- name: <php> install php
  yum:
    name: "{{ item }}"
    enablerepo: "{{ nginx_php_repo }}"
    state: present
  with_items: "{{ nginx_php_packages }}"

- name: <php> php date.timezone
  lineinfile:
    backup: yes
    path: /etc/php.ini
    state: present
    insertafter: ';date.timezone'
    regexp: '^date.timezone'
    line: 'date.timezone = "Asia/Tokyo"'

- name: <php> php default_charset
  lineinfile:
    backup: no
    path: /etc/php.ini
    state: present
    insertafter: ';default_charset'
    regexp: '^default_charset'
    line: 'default_charset = "UTF-8"'

- name: <php> php mbstring.language
  lineinfile:
    backup: no
    path: /etc/php.ini
    state: present
    insertafter: ';mbstring.language'
    regexp: '^mbstring.language'
    line: 'mbstring.language = "Japanese"'

- name: <php> phpfpm user
  lineinfile:
    backup: yes
    path: /etc/php-fpm.d/www.conf
    state: present
    insertafter: ';*user *='
    regexp: '^user *='
    line: 'user = nginx'

- name: <php> phpfpm group
  lineinfile:
    backup: no
    path: /etc/php-fpm.d/www.conf
    state: present
    insertafter: ';*group *='
    regexp: '^group *='
    line: 'group = nginx'

- name: <php> phpfpm listen.owner
  lineinfile:
    backup: yes
    path: /etc/php-fpm.d/www.conf
    state: present
    insertafter: ';*listen.owner'
    regexp: '^listen.owner'
    line: 'listen.owner = nginx'

- name: <php> phpfpm listen.group
  lineinfile:
    backup: no
    path: /etc/php-fpm.d/www.conf
    state: present
    insertafter: ';*listen.group'
    regexp: '^listen.group'
    line: 'listen.group = nginx'

- name: <php> phpfpm listen
  lineinfile:
    backup: no
    path: /etc/php-fpm.d/www.conf
    state: present
    insertafter: ';*listen *='
    regexp: '^listen *='
    line: 'listen = /var/run/php-fpm.sock'

- name: <php> start php-fpm
  service:
    name: php-fpm
    state: started

- name: <php> enable php-fpm
  service:
    name: php-fpm
    enabled: yes
