- name: <OS> update all anyway
  yum:
    name: '*'
    state: latest

- name: <OS> install something anyway
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ basic_packages }}"

- name: <OS> install something anyway
  yum:
    name: "{{ item }}"
    state: present
    enablerepo: 'epel'
  with_items: "{{ basic_packages_epel }}"
